
server:
  port: 8762

spring:
  application:
    name: service-hi
  boot:
    admin:
      client:
        url: http://localhost:8004
  rabbitmq:
    host: 120.79.23.207
    port: 5673
    username: liuye
    password: liuye

# 默认只暴露health 和 info 端点,下面配置展示所有
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/