
server:
  port: 8762

spring:
  application:
    name: service-hi
  boot:
    admin:
      client:
        url: http://localhost:8004
  rabbitmq:
    host: 120.79.23.207
    port: 5673
    username: guest
    password: guest


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/