
server:
  port: 8762

spring:
  application:
    name: service-hi
  boot:
    admin:
      client:
        url: http://localhost:8004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/